# =============================================================================
# NETLIFY CONFIGURATION FOR IMAGEANALYZER
# =============================================================================
# Place this file in the root of your repository (same level as package.json)

# =============================================================================
# BUILD CONFIGURATION
# =============================================================================
[build]
  # Command to build your frontend
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build"
  
  # Directory to deploy (where your built files are)
  publish = "frontend/dist"

# Build environment variables (separate section for proper TOML syntax)
[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"
  CI = "true"
  NODE_ENV = "production"

# =============================================================================
# REACT ROUTER SUPPORT (SPA)
# =============================================================================
# This makes React Router work properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =============================================================================
# SECURITY HEADERS
# =============================================================================
# These headers protect your app from attacks
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; connect-src 'self' https://*.onrender.com"

# =============================================================================
# PERFORMANCE OPTIMIZATION
# =============================================================================
# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"